name: mypresence
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  image_picker: 0.8.7+5
  get: 4.6.5
  firebase_core: 2.13.1
  firebase_auth: 4.6.2
  cloud_firestore: 4.8.0
  firebase_storage: 11.2.2
  convex_bottom_bar: 3.2.0
  intl: 0.18.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher/mypresence_logo.png"
  min_sdk_android: 21 
  

  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
  - assets/
  - assets/launcher/


